// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9a6ocVhkTeaK532kh9VzuaTbgtFqX5r8',
    appId: '1:267857985772:web:c862272c5dc61744b6e5c9',
    messagingSenderId: '267857985772',
    projectId: 'split-up-76627',
    authDomain: 'split-up-76627.firebaseapp.com',
    storageBucket: 'split-up-76627.appspot.com',
    measurementId: 'G-32ZL8HLKGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFegTPQOrTub38MJG3mxqUNMmMpWVl7o',
    appId: '1:267857985772:android:62f28dea7ffe732fb6e5c9',
    messagingSenderId: '267857985772',
    projectId: 'split-up-76627',
    storageBucket: 'split-up-76627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA34bOd28rSgNlZ2iukgVPJtdnFAQ7z-SY',
    appId: '1:267857985772:ios:479fb7e78358222eb6e5c9',
    messagingSenderId: '267857985772',
    projectId: 'split-up-76627',
    storageBucket: 'split-up-76627.appspot.com',
    iosBundleId: 'com.example.splitupapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA34bOd28rSgNlZ2iukgVPJtdnFAQ7z-SY',
    appId: '1:267857985772:ios:dc5c90c10438ce6ab6e5c9',
    messagingSenderId: '267857985772',
    projectId: 'split-up-76627',
    storageBucket: 'split-up-76627.appspot.com',
    iosBundleId: 'com.example.splitupapp.RunnerTests',
  );
}
